#!/bin/sh
### BEGIN INIT INFO
# Provides:          wbctxd
# Required-Start:    
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: wifibroadcast tx daemon
# Description:       starts wifibroadcast tx daemon
### END INIT INFO
 
# Actions
case "$1" in
    start)
        # START
        /home/pi/wifibroadcast_fpv_scripts/tx.sh > /dev/null &
        ;;
    stop)
        # STOP
        killall tx.sh
        ;;
    restart)
        # RESTART
				killall tx.sh
        /home/pi/wifibroadcast_fpv_scripts/tx.sh > /dev/null &
        ;;
esac
 
exit 0

